// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg-r5G9XSMohga9uJ8jO5RUPHawSGNIF8',
    appId: '1:303450658543:web:8a2801e16bc273f0d82d1a',
    messagingSenderId: '303450658543',
    projectId: 'ddnjobapp',
    authDomain: 'ddnjobapp.firebaseapp.com',
    storageBucket: 'ddnjobapp.firebasestorage.app',
    measurementId: 'G-DET6ZMYNJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz6R0sps9rCH0Nmf8P27df5Ew2DXx0SE0',
    appId: '1:303450658543:android:26f74843e76f8d81d82d1a',
    messagingSenderId: '303450658543',
    projectId: 'ddnjobapp',
    storageBucket: 'ddnjobapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-L09sxq1vmbBK4mYTmZxCal9DK0Z5FXQ',
    appId: '1:303450658543:ios:3f210a05f6d287e3d82d1a',
    messagingSenderId: '303450658543',
    projectId: 'ddnjobapp',
    storageBucket: 'ddnjobapp.firebasestorage.app',
    iosBundleId: 'com.kiplatform.kiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-L09sxq1vmbBK4mYTmZxCal9DK0Z5FXQ',
    appId: '1:303450658543:ios:3f210a05f6d287e3d82d1a',
    messagingSenderId: '303450658543',
    projectId: 'ddnjobapp',
    storageBucket: 'ddnjobapp.firebasestorage.app',
    iosBundleId: 'com.kiplatform.kiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg-r5G9XSMohga9uJ8jO5RUPHawSGNIF8',
    appId: '1:303450658543:web:f4f002ac250b5ec3d82d1a',
    messagingSenderId: '303450658543',
    projectId: 'ddnjobapp',
    authDomain: 'ddnjobapp.firebaseapp.com',
    storageBucket: 'ddnjobapp.firebasestorage.app',
    measurementId: 'G-YTZGLRGN5E',
  );

}